### PR TITLE
Update project for the new Swift syntax

### PR DESCRIPTION
**Pull request by AndrewSB**

### CODE REVIEW

**Comment by ACPK** [comment]
It failed to run for me because:
1. linker command failed with exit code 1 (use -v to see invocation
2. Undefined symbols for architecture x86_64:
   "_NSVariableStatusItemLength", referenced from:

**Comment by AndrewSB** [comment]
My latest commit should have fixed it. Try it now

**Comment by nolandc** [comment]
:+1: 

I also needed these changes to get the code working. Thanks @AndrewSB !

One more potential change: I was able to remove the `main.swift` file by adding a `@NSApplicationMain` declaration in `AppDelegate.swift`

**Comment by AndrewSB** [comment]
@NolanDC if you send my forked repo a PR I'll merge it and it to this one. If @supertommy ever comes back to it

**Comment by supertommy** [comment]
I really need to figure out why Github doesn't notify me of issues or PRs...

**Pull request merged**
